"""Refactor calls schema: rename call_id to provider_call_id, add materialized dashboard fields, add constraints.

Revision ID: 20250101000001
Revises: 20250101000000
Create Date: 2025-01-01 00:00:01.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20250101000001'
down_revision = '20250101000000'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1.1 Rename ambiguous column: calls.call_id → calls.provider_call_id
    op.alter_column('calls', 'call_id', new_column_name='provider_call_id')
    
    # 1.2 Add materialized dashboard fields to calls
    op.add_column('calls', sa.Column('headline', sa.Text(), nullable=True))
    op.add_column('calls', sa.Column('sentiment_label', sa.String(), nullable=True))
    op.add_column('calls', sa.Column('sentiment_score', sa.Double(), nullable=True))
    op.add_column('calls', sa.Column('duration_sec', sa.Integer(), nullable=True))
    
    # 1.3 Add CHECK constraints for enum-like fields
    # Note: PostgreSQL doesn't support altering column type to ENUM directly in Alembic
    # We'll add CHECK constraints instead
    op.execute("ALTER TABLE calls ADD CONSTRAINT chk_status CHECK (status IN ('queued', 'processing', 'completed', 'failed'))")
    op.execute("ALTER TABLE calls ADD CONSTRAINT chk_direction CHECK (direction IN ('inbound', 'outbound'))")
    
    # 1.4 Add constraint to call_summaries for unique summary per type
    op.create_unique_constraint('uq_call_summary_type', 'call_summaries', ['call_id', 'summary_type'])
    
    # 1.5 Add indexes for UI performance
    op.create_index('idx_calls_created_at_desc', 'calls', [sa.text('created_at DESC')])
    op.create_index('idx_calls_agent_created_desc', 'calls', ['agent_id', sa.text('created_at DESC')])
    op.create_index('idx_calls_customer_number', 'calls', ['customer_number'])
    op.create_index('idx_call_summaries_call_type_created_desc', 'call_summaries', ['call_id', 'summary_type', sa.text('created_at DESC')])
    
    # The dialogue_turns index already exists from the previous migration
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index('idx_call_summaries_call_type_created_desc', table_name='call_summaries')
    op.drop_index('idx_calls_customer_number', table_name='calls')
    op.drop_index('idx_calls_agent_created_desc', table_name='calls')
    op.drop_index('idx_calls_created_at_desc', table_name='calls')
    
    # Drop constraints
    op.drop_constraint('uq_call_summary_type', 'call_summaries', type_='unique')
    op.execute("ALTER TABLE calls DROP CONSTRAINT IF EXISTS chk_direction")
    op.execute("ALTER TABLE calls DROP CONSTRAINT IF EXISTS chk_status")
    
    # Remove added columns
    op.drop_column('calls', 'duration_sec')
    op.drop_column('calls', 'sentiment_score')
    op.drop_column('calls', 'sentiment_label')
    op.drop_column('calls', 'headline')
    
    # Rename column back
    op.alter_column('calls', 'provider_call_id', new_column_name='call_id')
    
    # ### end Alembic commands ###